# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.6.1
 
pipelines:
  default:
    - step:
        name: "create zip"
        script:
         - git archive -o example-$BITBUCKET_BUILD_NUMBER.tar.gz HEAD
        artifacts:
          - example-*.tar.gz
    - step:
        caches:
         - maven
        script: # Modify the commands below to build your repository.
          - mvn -B verify # -B batch mode makes Maven less verbose
          - pipe: atlassian/heroku-deploy:1.1.1 # set buildpack to Java (via Heroku)
            variables:
              HEROKU_API_KEY: a2d04b31-bc11-4d98-b63e-08bfac9b4e06
              HEROKU_APP_NAME: 'calculationator-gmquick'
              ZIP_FILE: example-$BITBUCKET_BUILD_NUMBER.tar.gz
              WAIT: 'true'